In [23]:
from sklearn import datasets
from sklearn import linear_model
import numpy as np 
from sklearn.model_selection import train_test_split 

In [24]:
regr = linear_model.LinearRegression() 
diabetes = datasets.load_diabetes() 

print(diabetes.data[:1])


print(diabetes.feature_names)



[[ 0.03807591  0.05068012  0.06169621  0.02187239 -0.0442235  -0.03482076
  -0.04340085 -0.00259226  0.01990749 -0.01764613]]
['age', 'sex', 'bmi', 'bp', 's1', 's2', 's3', 's4', 's5', 's6']


In [25]:

X = diabetes.data[: , np.newaxis, 2]  


In [26]:
print(X[:1])

[[0.06169621]]


In [27]:
diabetes.target

array([151.,  75., 141., 206., 135.,  97., 138.,  63., 110., 310., 101.,
        69., 179., 185., 118., 171., 166., 144.,  97., 168.,  68.,  49.,
        68., 245., 184., 202., 137.,  85., 131., 283., 129.,  59., 341.,
        87.,  65., 102., 265., 276., 252.,  90., 100.,  55.,  61.,  92.,
       259.,  53., 190., 142.,  75., 142., 155., 225.,  59., 104., 182.,
       128.,  52.,  37., 170., 170.,  61., 144.,  52., 128.,  71., 163.,
       150.,  97., 160., 178.,  48., 270., 202., 111.,  85.,  42., 170.,
       200., 252., 113., 143.,  51.,  52., 210.,  65., 141.,  55., 134.,
        42., 111.,  98., 164.,  48.,  96.,  90., 162., 150., 279.,  92.,
        83., 128., 102., 302., 198.,  95.,  53., 134., 144., 232.,  81.,
       104.,  59., 246., 297., 258., 229., 275., 281., 179., 200., 200.,
       173., 180.,  84., 121., 161.,  99., 109., 115., 268., 274., 158.,
       107.,  83., 103., 272.,  85., 280., 336., 281., 118., 317., 235.,
        60., 174., 259., 178., 128.,  96., 126., 28

In [28]:
from sklearn.datasets import load_iris

iris = load_iris()

In [29]:
print(iris.data)

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]
 [5.4 3.9 1.7 0.4]
 [4.6 3.4 1.4 0.3]
 [5.  3.4 1.5 0.2]
 [4.4 2.9 1.4 0.2]
 [4.9 3.1 1.5 0.1]
 [5.4 3.7 1.5 0.2]
 [4.8 3.4 1.6 0.2]
 [4.8 3.  1.4 0.1]
 [4.3 3.  1.1 0.1]
 [5.8 4.  1.2 0.2]
 [5.7 4.4 1.5 0.4]
 [5.4 3.9 1.3 0.4]
 [5.1 3.5 1.4 0.3]
 [5.7 3.8 1.7 0.3]
 [5.1 3.8 1.5 0.3]
 [5.4 3.4 1.7 0.2]
 [5.1 3.7 1.5 0.4]
 [4.6 3.6 1.  0.2]
 [5.1 3.3 1.7 0.5]
 [4.8 3.4 1.9 0.2]
 [5.  3.  1.6 0.2]
 [5.  3.4 1.6 0.4]
 [5.2 3.5 1.5 0.2]
 [5.2 3.4 1.4 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [5.4 3.4 1.5 0.4]
 [5.2 4.1 1.5 0.1]
 [5.5 4.2 1.4 0.2]
 [4.9 3.1 1.5 0.2]
 [5.  3.2 1.2 0.2]
 [5.5 3.5 1.3 0.2]
 [4.9 3.6 1.4 0.1]
 [4.4 3.  1.3 0.2]
 [5.1 3.4 1.5 0.2]
 [5.  3.5 1.3 0.3]
 [4.5 2.3 1.3 0.3]
 [4.4 3.2 1.3 0.2]
 [5.  3.5 1.6 0.6]
 [5.1 3.8 1.9 0.4]
 [4.8 3.  1.4 0.3]
 [5.1 3.8 1.6 0.2]
 [4.6 3.2 1.4 0.2]
 [5.3 3.7 1.5 0.2]
 [5.  3.3 1.4 0.2]
 [7.  3.2 4.7 1.4]
 [6.4 3.2 4.5 1.5]
 [6.9 3.1 4.

In [30]:
iris.keys

<function Bunch.keys>

In [31]:
print(iris.keys)

<built-in method keys of Bunch object at 0x16b2edc70>


In [34]:
X_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.2)

In [33]:
X_train,X_test,y_train,y_test = train_test_split(iris.data, iris.target,test_size=0.2)

In [35]:
from sklearn.neighbors import KNeighborsClassifier 
from sklearn import metrics 

In [36]:
num_neigh = 1 

In [37]:
knn = KNeighborsClassifier(n_neighbors = num_neigh) 
knn.fit(X_train, y_train) 

KNeighborsClassifier(n_neighbors=1)

In [38]:
y_pred = knn.predict(X_test) 
scores = metrics.accuracy_score(y_test, y_pred) 

In [39]:
print('n_neighbors가 {0:d}일때 정확도: {1:.3f}'.format(num_neigh, scores))

n_neighbors가 1일때 정확도: 1.000


In [41]:
for yy in zip(y_test,y_pred):
    print(yy,yy[0]==yy[1])

(2, 2) True
(1, 1) True
(1, 1) True
(0, 0) True
(0, 0) True
(1, 1) True
(0, 0) True
(0, 0) True
(1, 1) True
(0, 0) True
(2, 2) True
(2, 2) True
(2, 2) True
(0, 0) True
(1, 1) True
(2, 2) True
(2, 2) True
(2, 2) True
(1, 1) True
(0, 0) True
(0, 0) True
(0, 0) True
(0, 0) True
(1, 1) True
(2, 2) True
(2, 2) True
(2, 2) True
(1, 1) True
(0, 0) True
(2, 2) True


In [43]:
import pandas as pd
import seaborn as sns

In [45]:
life = pd.read_csv('./life_expectancy.csv')

In [51]:
life = life[['Life expectancy','Year','Alcohol',
             'Percentage expenditure', 'Total expenditure',
             'Hepatitis B', "Measles", 'Polio', 'BMI', 'GDP','Thinness 1-19 years', 'Thinness 5-9 years']]


In [52]:
sns.set(rc={'figure.figsize':(12,10)})

In [85]:
arr = np.arange(4).reshape(2,2)
print(arr)

[[0 1]
 [2 3]]


In [87]:
print(arr[0]) #첫행(0번째) 인덱싱 
print(arr[1]) #두번째행 인덱싱 

[0 1]
[2 3]


In [92]:
print(arr[0][0])

0


In [104]:
print(arr[0,1])

1


In [94]:
a = np.arange(10000).reshape(100,100)
%timeit a[0,50]

48.2 ns ± 0.342 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [95]:
a = np.arange(10000).reshape(100,100)
%timeit a[0][50]

92.5 ns ± 1.68 ns per loop (mean ± std. dev. of 7 runs, 10,000,000 loops each)


In [99]:
target=[0,1]

In [101]:
print(arr[target])

[[0 1]
 [2 3]]


In [105]:
print(arr[0,1])

1


In [106]:
arr = np.arange(20).reshape(4,5)
print(arr)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [107]:
print(arr[0:2])

[[0 1 2 3 4]
 [5 6 7 8 9]]


In [108]:
print(arr[[0,1]])

[[0 1 2 3 4]
 [5 6 7 8 9]]
